# Generated by Django 3.1.7 on 2021-03-11 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0004_auto_20210302_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('repository_url', models.URLField()),
                ('users', models.ManyToManyField(to='library.Author')),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('C', 'Closed'), ('A', 'Active')], max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='library.author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='todo_app.project')),
            ],
        ),
    ]
